[package]
name = "hash_sign_01"
version = "1.0.0"

[addresses]
HashSign="0x1ef6299a9a4ca6a505def26f9480593ea3d8a26d3fa3368c544a1c2822b3ee95"
aptos_framework = "0x1"


[dependencies]
AptosFramework = { git = "https://github.com/aptos-labs/aptos-core.git", subdir = "aptos-move/framework/aptos-framework", rev = "testnet" }
