[package]
name = "hash_sign_02"
version = "1.0.0"

[addresses]
HashSign="0xaee6dd051b012e88f486e6aa1d7775848edf5dab523679a663c47becc2767549"
aptos_framework = "0x1"


[dependencies]
AptosFramework = { git = "https://github.com/aptos-labs/aptos-core.git", subdir = "aptos-move/framework/aptos-framework", rev = "testnet" }
